import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import Link from "next/link";

// import { authOptions } from "@/app/api/auth/[...nextauth]";

import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Logout from "./logout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {!!session && <Logout />}
          {!session && <Link href="/login">Login</Link>}
        </div>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
